/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.rogue1.spark.data.auditor

class App {

    companion object {
        @JvmStatic fun main(args: Array<String>) {
             LaunchArgs().main(args)
        }
    }
}

